### PR TITLE
fix: lodash usage for esm

### PR DESCRIPTION
**Pull request by wpmiro**
Updated lodash import because there was an error

### CODE REVIEW

**Comment by yunsii** [comment]
I think you should file an issue to describe the detail.

**Comment by yunsii** [comment]
ref: https://github.com/yunsii/unplugin-svg-sprite/issues/15

**Comment by yunsii** [comment]
I cann't push commits directly?

**Comment by wpmiro** [comment]
> I cann't push commits directly?

I sent invite
https://github.com/mykulyncom/unplugin-svg-sprite/invitations

**Comment by yunsii** [comment]
Did you check https://stackoverflow.com/questions/63341296/github-pull-request-allow-edits-by-maintainers ? It didn't need any extra invitations.

**Comment by wpmiro** [comment]
Знімок екрана 2024-03-23 о 15 20 55

**Pull request merged**
